.gitignore, package.json, public/sitemap.xml
Something funky happened after I updated to `9.1.7`.
=> Fix API route not being deployed.

pages/about.js, pages/blog/fetching-data-with-swr.mdx, pages/blog/google-analytics-api-nextjs.mdx, pages/blog/how-to-print-in-react-using-iframes.mdx, pages/blog/mailchimp-next-js.mdx, pages/blog/next-prisma.mdx, pages/blog/nextjs-firebase-serverless.mdx, pages/blog/unsplash-api-nextjs.mdx, pages/blog/youtube-api-nextjs.mdx
Now the link just needs to become public... 🤞
=> Add new workshop to about page.

pages/blog/getting-started-with-dart-and-react.mdx
https://github.com/leerob/dart-react-todo/pull/5
=> Update Dart guide for 2020.

layouts/index.js, package.json, yarn.lock
React 2025 is almost finished, which means the product is almost ready! Once I switch over to the production DB, I'll merge this PR. For now, you can check out the deploy previews to see what it will look like 😄 
Feel free to leave some comments!
=> Add comments to blog with Fast Feedback.

layouts/index.js
Closes https://github.com/leerob/leerob.io/issues/216.
=> Add dark mode support for comments.

pages/blog/backend.mdx
Having spent 6+ years deeply entrenched in the WordPress world, I know firsthand how particular the community is about the spelling of their platform. To the point where they even have a built-in function to better enforce it ([capital_P_dangit](https://developer.wordpress.org/reference/functions/capital_p_dangit/)) and a [corresponding Twitter bot](https://twitter.com/capitalp_dangit?lang=en) that monitors for it and publicly corrects people. 😂
So all that to say... A simple PR to remedy that in your latest post. 😊
=> Fixes incorrect spelling of WordPress.

package.json, yarn.lock
=> Revert "Bump next from 9.5.3 to 9.5.4"

data/snippets/buttondown-subscribers.mdx, data/snippets/buttondown.mdx, data/snippets/firebase.mdx, data/snippets/google-analytics.mdx, data/snippets/google-sheets.mdx, data/snippets/gumroad-product.mdx, data/snippets/gumroad.mdx, data/snippets/mailchimp.mdx, data/snippets/mailgun.mdx, data/snippets/sendgrid.mdx, data/snippets/slack.mdx, data/snippets/spotify-top-tracks.mdx, data/snippets/spotify.mdx, data/snippets/stripe.mdx, data/snippets/youtube.mdx
Fixed the environment typo on every snippet page, great website btw!
=> Fix snippets mdx typos

.gitignore, next.config.js, package.json, scripts/generate-rss.js, yarn.lock
Closes https://github.com/leerob/leerob.io/issues/178.
There might be a better way to do this, but this is a valid RSS feed. Inspired by [shud.in](https://shud.in/) 👏
=> Add RSS feed.

layouts/blog.js
I noticed that your edit URLs were pointing to the non-existent `master` branch instead of the `main` branch
=> Point edit URL to main branch

pages/blog.js
Proposing an addition to make "No posts found." visible for the current theme.
=> "No posts found." in blog.js color scheme misalignment

styles/global.css
Hi Lee, this PR closes [#277](https://github.com/leerob/leerob.io/issues/277).
BTW, I'm currently learning NextJS and got inspired to start my own blog after watching your code walkthrough on youtube and your "React 2025" series. Thanks Lee!
=> Add fallback into browsers that don't support backdrop-filter by default

pages/tweets.js
My [spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) found this while I was poking through the code.
=> fix(pages): fixes typo in tweets page.

next.config.js, package.json, yarn.lock
Experimental feature, more info: https://twitter.com/hdjirdeh/status/1369709676271726599
=> Inline critical CSS.

next.config.js, package.json, yarn.lock
Reverts leerob/leerob.io#290. I see a flash of white, must not be working well with dark mode yet.
=> Revert "Inline critical CSS."

pages/_app.js
Closes https://github.com/leerob/leerob.io/issues/297.
=> Remove MDXProvider from _app.js.

components/Subscribe.js
=> fix for heading elements in order

components/Container.js
=> fix theme toggle button

next.config.js
=> Add security headers. (XSS, CSP)

components/MDXComponents.js, components/Tweet.js, data/blog/iowa-caucuses.mdx, data/blog/purpose-driven-work.mdx, lib/mdx.js, lib/twitter.js, package.json, pages/blog/[slug].js, styles/global.css, yarn.lock
Removes a dependency, some layout shift, and uses a completely static tweet component. Yay!
Closes https://github.com/leerob/leerob.io/issues/276.
=> Use StaticTweet component in MDX.

components/Container.js, styles/global.css
- Added styling to skip nav to fix display issue when in focus
Picture of issue:
=> Improved skip nav

pages/api/guestbook/[id].js, pages/api/guestbook/index.js, pages/guestbook.js
When I switched over to SQL, I forgot to keep this logic!
=> Don't return emails for Guestbook API.

components/BlogPost.tsx, components/Guestbook.tsx, components/NowPlaying.tsx, components/Subscribe.tsx, components/TopTracks.tsx, components/ViewCounter.tsx, components/metrics/Analytics.tsx, components/metrics/Github.tsx, components/metrics/Gumroad.tsx, components/metrics/Newsletter.tsx, components/metrics/Unsplash.tsx, components/metrics/Youtube.tsx, lib/types.ts
Closes https://github.com/leerob/leerob.io/issues/370.
=> Change Interfaces to Types.

styles/global.css, tailwind.config.js
Closes https://github.com/leerob/leerob.io/issues/378.
=> Fix table overflow.

styles/global.css
- adjust skip-nav to match the new layout
- added scroll-margin-top to the skip link (so the content doesn't stick
at the edge of the screen)
=> fix: skip-nav placement

components/Subscribe.tsx
Fixes the text moving below the button on the subscribe form
**Before**
**After**
=> fix(subscribe): padding right added to input field

data/blog/rust.mdx
The blog post contains more details.
=> rust: link to blog rome-will-be-rewritten-in-rust

data/blog/style-guides-component-libraries-design-systems.mdx
Replace `ttps://...` with `https://...`
=> Fix broken link to uxpin.com

pages/blog.tsx
Did this to improve performance.
=> Sort blogs in getStaticProps instead of on the client side

data/blog/devrel-at-vercel.mdx
- fixed a small typo in DevRel at Vercel post.
=> fixed typo in devrel at vercel post

data/blog/heroku.mdx
- timely → time-consuming
- one click → one-click
=> Minor edits to Heroku post

pages/blog.tsx, pages/snippets/index.tsx
Fixes issue #494 and the second issue in #487 
Before:
After:
=> fix: compile error due to incorrect import

pages/blog/[slug].tsx, pages/snippets/[slug].tsx
Closes https://github.com/leerob/leerob.io/issues/499.
=> Handle 404 when blog post doesn't exist from Sanity.

lib/spotify.ts
Closes https://github.com/leerob/leerob.io/issues/514.
=> Fix Spotify now playing.

README.md
hi Lee,
When I was copying this code snippet and paste in my terminal, it is giving me errors because the `$` was in there. 
Screenshot:
I am suggesting removing `$` in the code snippets, so it'll just work.
what do u think
=> chore: update readme code example

components/Guestbook.tsx
=> Fix overflowing text in guestbook page

app/page.tsx, lib/metrics.tsx
The function `getCommitCount` actually returned stargazers count, so I renamed it to `getStarCount` just in case it's a typo.
=> fix: typo (?)

content/backend.mdx
New messaging for our [new website](https://liveblocks.io). Still fits on 3 lines!
=> Updated Liveblocks messaging.

app/page.tsx
Remove the empty `className` attribute from `app/page.tsx`
=> Remove unnecessary `className` attribute.

components/sidebar.tsx
=> styles: hidden bar scroll in nav

app/actions.ts, app/admin/form.tsx, app/admin/page.tsx
This was fun. Getting all of the click / shift click / command click options for the checkboxes working how I'd expect from tools like Linear and such. Tried to do it without adding a library. And also wanted to make sure it works through the keyboard.
=> Add admin page for guestbook.

content/2023.mdx
That's about it, great article!
=> Fix minor typo in 2023.mdx

content/2023.mdx
https://vercel.com/postgres → https://vercel.com/storage/postgres
=> Fix postgres URL

app/global.css
it looks better with the dark scrollbar.
=> fix(css): use the dark scrollbar with `color-scheme` dark

setup.mjs
=> Fixed Typo: Not "orderride" but "override"

.env.example
reroute broken link in the env setup
=> fix: broken links
