leerob/site

styles/prism.js
This PR fixes an issue where highlighted code blocks show an extra empty line on Firefox, see j0lv3r4/mdx-prism#4.
Before:
After:
=> fix: Extra newline in highlighted code blocks

pages/blog/youtube-api-nextjs.mdx
Hi Rob!
I found your article about YouTube API integration extremely valuable, however one part didn't work for me.
Copy-pasting
```
const youtube = google.youtube({
auth,
version: 'v3'
})
```
has left me with `ReferenceError: auth is not defined`
I changed my code to
```
const youtube = google.youtube({
auth: googleAuth,
version: 'v3'
})
```
and it worked.
Just leaving it here. Totally possible that there are some assumptions in the article that I have missed. Anyway, since it scores quite high on Google, I recon that it should be more copy-paste friendly.
Irrelevant if the mistake is on my side.
Once again, thanks for the tutorial! Hope you're having a great day 😄
=> Fix google auth syntax in Next.js + YT article

tailwind.config.js
Fixes #242 
I am using `scroll-top-margin` offset.
Here is its compatibility: [caniuse](https://caniuse.com/?search=scroll-margin-top)
Working fine in chrome and firefox (mobile and desktop). 
Not sure about Safari :smile:
=> Sticky navbar covering headings

components/ConsCard.js
It had the same title description as ProsCard.js, so I included a 'not' in the text.
=> Fix important typo in ConsCard.js

layouts/blog.js
Hello!
Fantastic blog. Been looking at it for some inspiration for my own Next/MDX site :-) 
I noticed your "Share on Twitter" links are broken, resulting in the following: 
You'll notice the missing slash after blog. This PR adds that, ie `https://leerob.io/blogresume` -> `https://leerob.io/blog/resume`.
Hope it helps!
=> Add missing leading slash to "Discuss on Twitter" links

pages/api/github.js
By default, GitHub returns up to 30 repos in their response, and since you have more than that you are not counting a few stars.
Increasing the page size returns 47 repos and increases the stars from 1,787 to 2,970.
If you want to make this more future-proof you can request subsequent pages while there are more items, with something like this:
```js
export default async (_, res) => {
const userResponse = await fetch('https://api.github.com/users/leerob');
let repositories = [];
let page = 0;
let partialUserRepos = [];
do {
const userReposResponse = await fetch(
'https://api.github.com/users/leerob/repos?per_page=100&page=' + page
);
partialUserRepos = await userReposResponse.json();
repositories = repositories.concat(partialUserRepos);
page++;
} while (partialUserRepos.length === 100); …
```
=> Increasing the page size for the GitHub repos request

data/blog/spotify-api-nextjs.mdx, data/snippets/spotify-top-tracks.mdx, data/snippets/spotify.mdx, lib/spotify.js
From [Next.js docs](https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables):
> **Note**: In order to keep server-only secrets safe, Next.js replaces `process.env.*` with the correct values at build time. This means that `process.env` is not a standard JavaScript object, so you’re not able to use [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). Environment variables must be referenced as e.g. `process.env.NEXT_PUBLIC_PUBLISHABLE_KEY`, not `const { NEXT_PUBLIC_PUBLISHABLE_KEY } = process.env`.
=> Do not use destructuring for environment variables

components/Container.js
The toggle mode icon is not in sync when it respects the system mode
From the next-theme [FAQ](https://www.npmjs.com/package/next-themes#faq):
> When supporting the System theme preference, you want to make sure that's reflected in your UI. This means your buttons, selects, dropdowns, or whatever you use to indicate the current theme should say "System" when the System theme preference is active.
> 
> If we didn't distinguish between theme and resolvedTheme, the UI would show "Dark" or "Light", when it should really be "System".
=> Fix toggle mode icon mismatch

next.config.js
https://www.theverge.com/2021/3/30/22358287/privacy-ads-google-chrome-floc-cookies-cookiepocalypse-finger-printing
=> Update security headers to opt-out of Google's FLoC.

scripts/generate-sitemap.js
I noticed you have a link duplication in your sitemap (https://leerob.io/uses). This is due to the sitemap generator script add uses from 2 places:
1- The pages directory ( uses.js )
2- The data directory ( uses.mdx )
By excluding the top level of the data directory ( which you use for some pages i guess?) then the generator will add the page only from pages directory.
I also excluded the 404 page, not sure if you wanna keep it or not ( and maybe add 500 for the future! )
You can test for duplicates here https://www.mysitemapgenerator.com/service/check.html
=> - Fix sitemap links duplication

pages/api/now-playing.js
Spotify can also be used to listen to podcast instead of songs
I noticed when I was listening to a podcast rather than a song on spotify, the api returned a typeerror
because the song response json was 
the returned json doesnt offers much in terms of podcast, so i think it will be better to return not playing as output
=> fix type error while listening to a podcast on spotify

data/snippets/google-sheets.mdx
The code snippet was throwing the following error -
```js
error:0909006C:PEM routines:get_name:no start line
```
It seemed like the `PRIVATE_KEY` has to be parsed and should not include any `/` and `\n`.
The output has to be multi-line as follows: -
```
-----BEGIN PRIVATE KEY-----
<key>
-----END PRIVATE KEY-----
```
We can easily do this using the replace method.
Here is where I found the fix!
https://github.com/theoephraim/node-google-spreadsheet/issues/244
=> Error:0909006C:PEM No start line

data/blog/mdx.mdx
Closes https://github.com/leerob/leerob.io/issues/360.
=> Fix incorrect link to `rehype-prism-plus`

data/blog/fetching-data-with-swr.mdx
Updated the source link for metric card with a permalink blob
Note: Not for hacktober
=> fix: broken link metric card

components/Tweet.tsx
Fixes #390 - Large numbers from comments, retweets, and likes cause the Tweet component to overflow on smaller screen devices.
Before:
After:
=> Use compact notation for Tweet component

data/blog/css-with-react.mdx
Deleted this line "You don't want to configure a toolchain like PurgeCSS to use it effectively." because Tailwind no longer uses PurgeCSS under the hood.
=> Delete outdated information in a blog

styles/global.css
I noticed an underline under the "#" on the article anchors when you stop hovering.
Setting `no-underline` on `.prose .anchor` fixes this issue, and we can also remove it on a couple of other selectors.
=> fix: anchor underline bug

next.config.js, package.json, yarn.lock
Update to use the latest version of preact ([10.6.6](https://github.com/preactjs/preact/releases/tag/10.6.6)).
=> chore: update preact to 10.6.6

next.config.js
https://github.com/vercel/next.js/pull/36584
Should be about 7% faster: https://estimator.dev/#leerob.io
**Default targets:**
- Chrome 61
- Edge 16
- Firefox 60
- Opera 48
- Safari 11
=> Decrease JS by targeting modern browsers only.

pages/api/revalidate.ts
This PR fixes ISR revalidation.
[@sanity/webhook](https://github.com/sanity-io/webhook-toolkit) recommends verifying raw request body - see [migration guide](https://github.com/sanity-io/webhook-toolkit#migration).
Related issues:
- #532 
- #497
=> Fix on demand ISR revalidation with Sanity webhook

pages/api/views/[slug].ts
Solves #575 
I was playing around with my [own fork](https://shreyans-sh.vercel.app) and the view count on posts wasn't updating so after some searching I found that new posts with no DB entry were returning 0 before the POST request could execute.
Signed-off-by: Shreyans Jain <shreyansthebest2007@gmail.com>
=> fix: view count update on new posts

components/sidebar.tsx
by accident I ended up not removing the class and overwriting the one that already existed.
=> refactor: remove classe overflow-scroll in nav

next.config.js
Update CSP rule for font-src 'self' to have data as it is currently violated when using the next/font/local
=> Update CSP rule for font-src 'self' to have data

app/blog/[slug]/page.tsx
- See JSON-LD parsing issue here: https://search.google.com/test/rich-results/result/r%2Funknown-type?id=hOhPSaX_jG6RqnHFJpLidA
- Fix according to the Next.js docs: https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld
=> Fix LD-JSON parsing error

content/using-nextjs.mdx
Small fix, team's name is Learning and Advocacy. 🙂
=> Update using-nextjs.mdx, correct Meta team name

README.md
Since Next.js 14, the minimum required Node.js version is now 18.17
=> Update README for Node.js version

app/blog/[slug]/page.tsx
Append hard-coded THH:MM:SS or 00:00:00 if no time component exists in publishedAt frontmatter property of MDX.
Addresses #681
=> Append hard-coded time to publishedAt MDX frontmatter to prevent off-by-one day error

content/rust.mdx
This commit fixes the invalid date in the Rust blog post 🙂.
=> Update publishedAt in rust.mdx

app/global.css
Fixes the color of `property` and `entity` strings in light mode.
=> fix: syntax color for light mode

.prettierrc.json, package.json
This configuration is pretty minimal and is equivalent to setting
```json
"prettier.singleQuote": true
```
in VS Code's user settings.
The difference is that now this setting is picked up by the `prettier` CLI or others editors that use `prettier` to format.
=> Add one-rule prettier config to prefer single quotes

app/page.tsx
Hey! While browsing the website I noticed one detail that I think is not working as it should.
Only the logos of the startups are wrapped with links, not the buttons themselves, which should also be clickable for the user
I added minimal changes to fix this. The block from startups now consists of links with logos (before div > a > svg)
Let me know what you think about this.
=> Fix clickable area of startup links

app/layout.tsx
The view transition with your name looks a bit weird when a scrollbar appears, because the content is shifted slightly. Fixed by setting [`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) to `stable`.
Awesome redesign, love the simplicity!
=> Stable scrollbar

app/name.tsx
=> Fixing #735
